version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongodb:27017/resumeai?authSource=admin
      - ENV=development
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - .:/app
    command: ["/app/entrypoint.sh"]

volumes:
  mongodb_data:
