services:
  # db:
  #   image: pgvector/pgvector:pg17
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER=${DB_USER}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #     - POSTGRES_DB=${DB_NAME}
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #     start_period: 10s

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ENV=development
    # depends_on:
    #   db:
    #     condition: service_healthy
    volumes:
      - .:/app
    command: ["/app/entrypoint.sh"]
    expose:
      - "8000"
    networks:
      - resumeai

volumes:
  postgres_data:

networks:
  resumeai:
    driver: bridge